version: '3'

services:
  eclipse-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"